---
name: docker-python
description: Use docker image in action instead of container.image
inputs:
  make_args:
    description: make args
    required: true
branding:
  color: yellow
  icon: upload-cloud
runs:
  using: docker
  image: actions/Dockerfile
  args:
  - ${{ inputs.make_args }}
